### ISSUE TITLE
LDtkLevelData generation seems wrong and some features/documentation seems missing

### ISSUE THREAD

**Issue by NitroPlum** [IrishBruse/LDtkMonogame#15]
There are 2 issues relating to LDTKLevelData.

1) LevelData is being generated as a class that implements ILDtkEntity. This makes no sense and also doesn't work. Below was generated: 

```
public class LDtkLevelData : ILDtkEntity
{
    public string Identifier { get; set; }
    public System.Guid Iid { get; set; }
    public int Uid { get; set; }
    public Vector2 Position { get; set; }
    public Vector2 Size { get; set; }
    public Vector2 Pivot { get; set; }
    public Rectangle Tile { get; set; }
    public Color SmartColor { get; set; }
    public LevelType LevelType { get; set; }
}
```

2) The docs don't explain how you are supposed to load level data with Generated types. I would assume we would want something like `getLevelData<T>(level)` or something but I don't see anything similar anywhere in the docs or repo.

**Comment by IrishBruse** [comment]
Yeah you are right when I rewrote the importer last month I forgot to add this back in very sorry about that.
