### ISSUE TITLE
Feature Request: Add a toggle to use old-style Namespaces

### ISSUE THREAD

**Issue by NitroPlum** [IrishBruse/LDtkMonogame#16]
I propose a flag that allows me to use old-style namespaces. If you use older versions of C# for targeting console, the code produced by the generator doesn't work as it's not valid code. I would be willing to make a PR.

Examples:

Currently Generated :
```
namespace MyNamespace;
public void MyClass{}
```

Desired Generation or Optional Formet:

```
namespace MyNamespace {
    public void MyClass{}
}
```

**Comment by IrishBruse** [comment]
you can just specify the c# version in the csproj, whats the reason you are using older versions?
