### ISSUE TITLE
Allow relative paths to assets

### ISSUE THREAD

**Issue by MichielMag** [IrishBruse/LDtkMonogame#18]
I've noticed that LDTK saves a relative path to the tileset files, i.e. "..\images\tileset.png". 
When using this directly this line will fail: 
https://github.com/IrishBruse/LDtkMonogame/blob/fadfecf1cf019b2795ed5dddb108b143967411bd/LDtk/Renderer/LDtkRenderer.cs#L171

A solution would be to set LDtkLevel.FilePath and use that to allow relative loading. PR incoming.

**Comment by IrishBruse** [comment]
No clue why I hard coded "Content" into that part thanks for the bug report.
