### ISSUE TITLE
Loading the same tileset everytime LDtkRenderer draws a tile

### ISSUE THREAD

**Issue by kohrabi** [IrishBruse/LDtkMonogame#26]
hi, I'm trying to write a LDtkRenderer for my game using nez based on LDtkRenderer.cs and I notice that when I tried to use RenderLevel instead of PrerenderLevel my game began to drop fps(down to 30fps). After a bit of digging, I found that GetTexture is just loading the same tileset that had been loaded before into the memory everytime the Renderer tried to draw a sprite. I think maybe you can use the "tilesets" field in there and create a list of tilesets and make it faster maybe. I'm trying to write my own too. and sorry for the broken english but hope this help

**Comment by kohrabi** [comment]
wait no sorry. i'm just retarded

**Comment by IrishBruse** [comment]
The ldtk renderer is just an example to get something rendering quickly it's intended that you will make your own for custom rendering. Copy paste it into your project and make the changes you want. You should be using the pre rendered version anyways in the one I provide as it's alot faster.

**Comment by IrishBruse** [comment]
But thanks for pointing that out I will cache the textures for that version

**Comment by kohrabi** [comment]
alright. thanks
