### ISSUE TITLE
Help: How to pre-render individual layers?

### ISSUE THREAD

**Issue by PixelDough** [IrishBruse/LDtkMonogame#28]
I have multiple layers, one intended for the foreground and one intended for the background. The player need to render between these layers. Is there a way to pre-render individual layers, and subsequently draw individual layers?

Would the simplest way be making new instances of LDtkLevel for each layer?

**Comment by PixelDough** [comment]
Just tried making each layer into a separate LDtkLevel, but that will not work since I don't have access to the Identifier property on the level, which is null if a simply make a new instance of LDtkLevel

**Comment by IrishBruse** [comment]
https://github.com/IrishBruse/LDtkMonogame/blob/feature-ideas/LDtk/Renderer/LDtkRenderer.cs
I think there is a bug on the renderer you can customize it like this and the layers should be rendered separately for custom rendering you have to make a custom ldtk renderer use the one linked as a base.

**Comment by PixelDough** [comment]
Ahh I see! I went ahead and added functionality for pre-rendering layers and rendering those pre-rendered layers in the base LDtkRenderer in my own fork. I think it would be nice to have in the built in LDtkRenderer, but if you would like to keep the base one limited to just rendering levels as a whole, I will reimplement it in my own class :)

**Comment by IrishBruse** [comment]
You dont need to make a fork just make a LDtkRenderer file the one apart of the library is just an example as its not possible for me to know what the user would need or if they want to create a custom effect on each layer like what you want to do. Nothing in the ldtk renderer file is internal

**Comment by IrishBruse** [comment]
Its mentioned in the docs 
![image](https://github.com/IrishBruse/LDtkMonogame/assets/14964651/84b8c2b7-810f-4b8c-a219-438d4768966e)
