### ISSUE TITLE
Semi-transparent tiles not shown correctly

### ISSUE THREAD

**Issue by SlateyDev** [IrishBruse/LDtkMonogame#31]
While trying the built in example "Typical_2D_platformer_example.ldtk" I was getting differences in what was drawn with LDtk/bevy_ecs_ldtk and LDtkMonogame. While both LDtk and bevy_ecs_ldtk show the Wall_shadows the same way, LDtkMonogame appears to be more opaque.

![image](https://github.com/IrishBruse/LDtkMonogame/assets/7058638/879967fc-7e62-4659-afa4-470a81f251b3)
LDtk

![image](https://github.com/IrishBruse/LDtkMonogame/assets/7058638/401d2a91-4951-4bbf-96f9-54694b4524c1)
bevy_ecs_ldtk

![image](https://github.com/IrishBruse/LDtkMonogame/assets/7058638/6f3882de-5087-4964-8256-ba6de9b21e35)
LDtkMonogame

This makes the level look quite off.

**Comment by IrishBruse** [comment]
Should be fixed now will release a new version with this fixed. Thanks for bug report just so you know if you need to render stuff differently than the example renderer comes with you can make your own for example if you needed parallax, blurring or something custom. Just copy the renderer code and make the changes you need
