### ISSUE TITLE
Support for xnb files

### ISSUE THREAD

**Issue by Shmellyorc** [IrishBruse/LDtkMonogame#5]
Please add support for the xnb files instead of exposing png files. An example would be use the tilesetrelpath but remove the extension and try to content.load(...) where the current tileset png path would be.

@ World.cs : LoadAllLayers(...) =>
`
texture = Texture2D.FromFile(GraphicsDevice, Path.Combine(this.projectFolder, jsonLayerInstance.TilesetRelPath));
`

**Comment by IrishBruse** [comment]
Yup will do just faster to handle it without while developing can add support for that for the next release
