### ISSUE TITLE
Request: Make the utility class public

### ISSUE THREAD

**Issue by fossegutten** [IrishBruse/LDtkMonogame#7]
Would like to make my own world/level classes with your library

**Comment by IrishBruse** [comment]
https://github.com/IrishBruse/LDtkMonogame/blob/main/LDtkMonogame.Examples/Source/CustomizedLevel.cs
https://github.com/IrishBruse/LDtkMonogame/blob/cb37165715e053fb06fbc2c13bf15dbdb7c8c855/LDtkMonogame.Examples/Source/Utility/LevelManager.cs#L32
You can take a look at the examples the library injects the data into the classes you pass to it so variables in ldtk are passed to the classes in the same way as entities
Been meaning to update the documentation on the website sorry about the confusion

**Comment by fossegutten** [comment]
Yeah, I would like to just access all data instead of having to use the entity and world scripts you made. I already created entity class in my game. would be nice to separate the data and rendering, like in Monogame Extended Tiled. You can also draw separate layers there.

**Comment by IrishBruse** [comment]
Yeah you can also render layers separately with this I'm confused what data it is you need as the functions just return a class or struct with all the data from the entity/level there is no underlying data as its stored in json in separate entities like I'm returning to you. you also don't need to use the entity class you can pass a completely separate not inheriting class as long as it has all the fields name the same as in ldtk it will also populate the class with the data the inheritance is just for simplicity.

**Comment by IrishBruse** [comment]
I'm going to close this now if you still have questions feel free to open another issue.
