### ISSUE TITLE
Missing LDtkMonogame.ContentPipeline.dll

### ISSUE THREAD

**Issue by kimbo12** [IrishBruse/LDtkMonogame#8]
Missing LDtkMonogame.ContentPipeline.dll for importing with mgcb.

**Comment by IrishBruse** [comment]
you have to compile it in the github its still experimental i havent finished it yet when i get some free time again ill work on the importer sorry thats why its not in the nuget package

**Comment by kimbo12** [comment]
Understood, thank you!

**Comment by IrishBruse** [comment]
A dedicated package is now available for the content pipeline
https://www.nuget.org/packages/LDtkMonogame.ContentPipeline/
I will have documentation up on the wiki soon on how to add it but you just need to add a ref to the dll
